### PR TITLE
Added sleep for 5 seconds, if the endpoint is not available, yet.

### PR DESCRIPTION
**Pull request by DracoBlue**

### CODE REVIEW

**Comment by jimmywarting** [comment]
I don't think i like this one... it will halt all the execution.
I would rather want to do a setTimeout or setInterval

heck i even think i would throw in a generator and do something like:

```javascript
while(runing){
  yield heartbeat()
}
```

And call it like this
```javascript
setInterval(generatorFn.next, 5000)
```

But this is just one of many way to do it...

**Comment by jimmywarting** [comment]
if i'm not mistaking this will also take a lot of cpu while calling `date.getTime` multiple times

**Comment by jimmywarting** [comment]
could also do something like

think it would also be possible to do:

`await sleep(5)` where sleep is a promise that will resolve after 5 sec with setTimeout...

**Comment by DracoBlue** [comment]
It does not do a busy wait, but you are right: something like setTimeout would be better. Or using setInterval until it works.

**Comment by jimmywarting** [comment]
I have replaced it with a simple promise for now... if we ever decide to implement a sleep util fn that can be useful. then we can use it. but for now i only see one place where it fits:

https://github.com/stoffern/pokemon-go-api/commit/5d90e4480d860e8f796bd1574961d16ca41b7db7

**Comment by DracoBlue** [comment]
:+1:

**Pull request merged**
